apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-app
  template:
    metadata:
      labels:
        app: cicd-app
    spec:
      containers:
      - name: cicd-container
        image: cicd-python-app
        imagePullPolicy: Never
        command: ["python", "CICD_Pipeline.py"]
